extends:
  - profile: debian.yaml

packages:
  - zlib
  - szlib
  - python:
      use: host-python
  - numpy:
      use: host-numpy
  - scipy:
      use: host-scipy
  - nose
  - launcher
  - hdf5

  - gmp
  - mpfr

  - jinja2
  - distribute

  - mpi:
      use: host-mpi
