parameters:
- name: version
  type: version
  default: 2.8.0

- name: relocatable
  type: bool
  default: false

extends: [autotools_package]

dependencies:
  build: [pkg-config, freetype, libxml2, zlib, bzip2, python]
  run: [pkg-config]

sources:
- url: http://www.freedesktop.org/software/fontconfig/release/fontconfig-{{version}}.tar.gz
  key:
    when version == 2.8.0: tar.gz:7ivby3xkmvgz7tt2jmjcb4imthg6zben
    when version == 2.9.0: tar.gz:zj7ckby46bcl3tnppreiiusdyek3sju3
    when version == 2.11.1: tar.gz:w2ygnr644p2dn7oa365otu3bekzybfhu

when_build_dependency:
- prepend_path: PKG_CONFIG_PATH
  value: '${ARTIFACT}/lib/pkgconfig'
- prepend_path: PATH
  value: '${ARTIFACT}/bin'
