parameters:
- name: version
  type: version
  default: 0.12.2

extends: [setuptools_package]

dependencies:
  run: [yaml, python-markdown, livereload, ghp_import]

sources:
- url: https://pypi.python.org/packages/source/m/mkdocs/mkdocs-{{version}}.tar.gz
  key:
    when version == 0.12.2: tar.gz:5bywnfxh5lrfod3vex4octke7zz7p4gi
