extends: [autotools_package]

sources:
- url: http://pkgconfig.freedesktop.org/releases/pkg-config-0.28.tar.gz
  key: tar.gz:nnxlghdoyrbbc5cxqzjmpykb7wvofwv2

build_stages:
- name: configure
  extra: ['--with-internal-glib']

when_build_dependency:
- prepend_path: PATH
  value: '${ARTIFACT}/bin'
- set: PKG_CONFIG_EXECUTABLE
  value: '${ARTIFACT}/bin/pkg-config'
