extends: [setuptools_package]

dependencies:
  build: []
  run: []

sources:
 - key: tar.gz:oco2v4dxvivthpw2yetqmnzuclbwqnlw
   url: https://pypi.python.org/packages/87/35/4af9634270c00e3411cf951b7e0ea796c262922357cfc7609a86d31f072b/pkgconfig-1.1.0.tar.gz
